// <auto-generated />
namespace ReservationApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addadditionaldataannotationsformodelclasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addadditionaldataannotationsformodelclasses));
        
        string IMigrationMetadata.Id
        {
            get { return "201909132249056_Add additional data annotations for model classes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
